const movies = [
  {
    adult: false,
    backdrop_path: '/20uHjZ4yCPD2x0ndcxZaxM7hLIy.jpg',
    id: 493529,
    title: 'Dungeons \u0026 Dragons: Honor Among Thieves',
    original_language: 'en',
    original_title: 'Dungeons \u0026 Dragons: Honor Among Thieves',
    overview:
      'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
    poster_path: '/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg',
    media_type: 'movie',
    genre_ids: [12, 14, 35],
    popularity: 507.373,
    release_date: '2023-03-23',
    video: false,
    vote_average: 7.533,
    vote_count: 658,
  },
  {
    adult: false,
    backdrop_path: '/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg',
    id: 640146,
    title: 'Ant-Man and the Wasp: Quantumania',
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 9200.005,
    release_date: '2023-02-15',
    video: false,
    vote_average: 6.548,
    vote_count: 2108,
  },
  {
    adult: false,
    backdrop_path: '/44immBwzhDVyjn87b3x3l9mlhAD.jpg',
    id: 934433,
    title: 'Scream VI',
    original_language: 'en',
    original_title: 'Scream VI',
    overview:
      'Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.',
    poster_path: '/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg',
    media_type: 'movie',
    genre_ids: [27, 9648, 53],
    popularity: 3854.657,
    release_date: '2023-03-08',
    video: false,
    vote_average: 7.351,
    vote_count: 929,
  },
  {
    adult: false,
    backdrop_path: '/8HfjrSxfTVKmjNh8cJjbu5eXzcX.jpg',
    id: 420808,
    title: 'Peter Pan \u0026 Wendy',
    original_language: 'en',
    original_title: 'Peter Pan \u0026 Wendy',
    overview:
      'Wendy Darling, a young girl afraid to leave her childhood home behind, meets Peter Pan, a boy who refuses to grow up. Alongside her brothers and a tiny fairy, Tinker Bell, she travels with Peter to the magical world of Neverland. There, she encounters an evil pirate captain, Captain Hook, and embarks on a thrilling adventure that will change her life forever.',
    poster_path: '/9NXAlFEE7WDssbXSMgdacsUD58Y.jpg',
    media_type: 'movie',
    genre_ids: [10751, 14, 28, 12],
    popularity: 311.87,
    release_date: '2023-04-20',
    video: false,
    vote_average: 5.995,
    vote_count: 206,
  },
  {
    adult: false,
    backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
    id: 502356,
    title: 'The Super Mario Bros. Movie',
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview:
      'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    media_type: 'movie',
    genre_ids: [16, 12, 10751, 14, 35],
    popularity: 6128.924,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.487,
    vote_count: 1695,
  },
  {
    adult: false,
    backdrop_path: '/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg',
    id: 868759,
    title: 'Ghosted',
    original_language: 'en',
    original_title: 'Ghosted',
    overview:
      'Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.',
    poster_path: '/liLN69YgoovHVgmlHJ876PKi5Yi.jpg',
    media_type: 'movie',
    genre_ids: [10749, 28, 35],
    popularity: 4667.034,
    release_date: '2023-04-18',
    video: false,
    vote_average: 7.253,
    vote_count: 525,
  },
  {
    adult: false,
    backdrop_path: '/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg',
    id: 758323,
    title: "The Pope's Exorcist",
    original_language: 'en',
    original_title: "The Pope's Exorcist",
    overview:
      "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    poster_path: '/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg',
    media_type: 'movie',
    genre_ids: [27, 9648, 53],
    popularity: 1798.764,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.197,
    vote_count: 272,
  },
  {
    adult: false,
    backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
    id: 76600,
    title: 'Avatar: The Way of Water',
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    media_type: 'movie',
    genre_ids: [878, 12, 28],
    popularity: 4048.285,
    release_date: '2022-12-14',
    video: false,
    vote_average: 7.712,
    vote_count: 7723,
  },
  {
    adult: false,
    backdrop_path: '/e7FzphKs5gzoghDotAEp2FeP46u.jpg',
    id: 649609,
    title: 'Renfield',
    original_language: 'en',
    original_title: 'Renfield',
    overview:
      "Having grown sick and tired of his centuries as Dracula's lackey, Renfield finds a new lease on life — and maybe even redemption — when he falls for feisty, perennially angry traffic cop Rebecca Quincy.",
    poster_path: '/p6yUjhvNGQpFZilKwOKbxQ1eHlo.jpg',
    media_type: 'movie',
    genre_ids: [27, 35, 14],
    popularity: 209.828,
    release_date: '2023-04-07',
    video: false,
    vote_average: 7.227,
    vote_count: 154,
  },
  {
    adult: false,
    backdrop_path: '/rbuahTzRqThIc9JOG60fQzPXJtH.jpg',
    id: 447365,
    title: 'Guardians of the Galaxy Volume 3',
    original_language: 'en',
    original_title: 'Guardians of the Galaxy Volume 3',
    overview:
      'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
    poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    media_type: 'movie',
    genre_ids: [878, 12, 28],
    popularity: 780.586,
    release_date: '2023-05-03',
    video: false,
    vote_average: 8.4,
    vote_count: 76,
  },
  {
    adult: false,
    backdrop_path: '/wybmSmviUXxlBmX44gtpow5Y9TB.jpg',
    id: 594767,
    title: 'Shazam! Fury of the Gods',
    original_language: 'en',
    original_title: 'Shazam! Fury of the Gods',
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    poster_path: '/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg',
    media_type: 'movie',
    genre_ids: [28, 35, 14, 12],
    popularity: 3887.11,
    release_date: '2023-03-15',
    video: false,
    vote_average: 6.832,
    vote_count: 1395,
  },
  {
    adult: false,
    backdrop_path: '/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg',
    id: 713704,
    title: 'Evil Dead Rise',
    original_language: 'en',
    original_title: 'Evil Dead Rise',
    overview:
      'Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.',
    poster_path: '/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg',
    media_type: 'movie',
    genre_ids: [27],
    popularity: 1528.922,
    release_date: '2023-04-12',
    video: false,
    vote_average: 7.025,
    vote_count: 318,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1260.564,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1282,
  },
  {
    adult: false,
    backdrop_path: '/eEF40Xk2twM3WjRNZftfo771gjv.jpg',
    id: 700391,
    title: '65',
    original_language: 'en',
    original_title: '65',
    overview:
      '65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.',
    poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
    media_type: 'movie',
    genre_ids: [878, 12, 53],
    popularity: 1187.041,
    release_date: '2023-03-02',
    video: false,
    vote_average: 6.261,
    vote_count: 879,
  },
  {
    adult: false,
    backdrop_path: '/zh614Bixv2ePaHK8gzcUpUmcvYv.jpg',
    id: 1102776,
    title: 'AKA',
    original_language: 'fr',
    original_title: 'AKA',
    overview:
      "A steely special ops agent finds his morality put to the test when he infiltrates a crime syndicate and unexpectedly bonds with the boss' young son.",
    poster_path: '/3BSxAjiporlwQTWzaHZ9Yrl5C9D.jpg',
    media_type: 'movie',
    genre_ids: [53, 28, 80],
    popularity: 183.764,
    release_date: '2023-04-28',
    video: false,
    vote_average: 6.758,
    vote_count: 93,
  },
  {
    adult: false,
    backdrop_path: '/bF2skCyB5jeJuO26GFaQIGHrMNl.jpg',
    id: 1085103,
    title: 'Clock',
    original_language: 'en',
    original_title: 'Clock',
    overview:
      'On the eve of her 38th birthday, a woman desperately attempts to fix her broken biological clock.',
    poster_path: '/bkPpmNSdbRIgtscqH86BQFLJXcz.jpg',
    media_type: 'movie',
    genre_ids: [27, 9648, 53],
    popularity: 54.708,
    release_date: '2023-03-28',
    video: false,
    vote_average: 6.3,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: '/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg',
    id: 948713,
    title: 'The Last Kingdom: Seven Kings Must Die',
    original_language: 'en',
    original_title: 'The Last Kingdom: Seven Kings Must Die',
    overview:
      "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
    poster_path: '/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 36, 18, 10752],
    popularity: 3286.846,
    release_date: '2023-04-14',
    video: false,
    vote_average: 7.306,
    vote_count: 281,
  },
  {
    adult: false,
    backdrop_path: '/7TdVWAO7vV9j1OLDq1hQJS3pb4U.jpg',
    id: 739405,
    title: 'Operation Fortune: Ruse de Guerre',
    original_language: 'en',
    original_title: 'Operation Fortune: Ruse de Guerre',
    overview:
      "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
    poster_path: '/uo7vWfQUlVwueYTDRicXOJa8Oow.jpg',
    media_type: 'movie',
    genre_ids: [28, 35, 12],
    popularity: 131.003,
    release_date: '2023-01-04',
    video: false,
    vote_average: 6.658,
    vote_count: 623,
  },
  {
    adult: false,
    backdrop_path: '/vcNXzOfACCXZA7vb8SNde0LUC9o.jpg',
    id: 1068141,
    title: 'Mighty Morphin Power Rangers: Once \u0026 Always',
    original_language: 'en',
    original_title: 'Mighty Morphin Power Rangers: Once \u0026 Always',
    overview:
      "After tragedy strikes, an unlikely young hero takes her rightful place among the Power Rangers to face off against the team's oldest archnemesis.",
    poster_path: '/vc87upO8vcAGj9OmgH3AIz6ikKB.jpg',
    media_type: 'movie',
    genre_ids: [28, 878, 14],
    popularity: 130.019,
    release_date: '2023-04-19',
    video: false,
    vote_average: 6.796,
    vote_count: 152,
  },
  {
    adult: false,
    backdrop_path: '/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg',
    id: 677179,
    title: 'Creed III',
    original_language: 'en',
    original_title: 'Creed III',
    overview:
      'After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian — a fighter who has nothing to lose.',
    poster_path: '/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg',
    media_type: 'movie',
    genre_ids: [18, 28],
    popularity: 3125.645,
    release_date: '2023-03-01',
    video: false,
    vote_average: 7.257,
    vote_count: 1253,
  },
]

export type Movie = (typeof movies)[number]

export default movies
